### ISSUE TITLE
いいところ診断の結果に優しさを追加したい

### ISSUE THREAD

**Issue by hatoym** [hatoym/assessment#1]
以下の結果を追加したい

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振る舞いに多くの人が癒やされています。'

**Comment by hatoym** [comment]
これから対応します。

**Comment by naru380** [comment]
f757de1 で対応されました。

**Comment by hatoym** [comment]
f757de1 で対応されました。
